### ISSUE TITLE
API only mode

### ISSUE THREAD

**Issue by Mrjaco12** [spartansystems/spartan-composer-recipes#23]
in a regular rails app you can call `rails new app_name --api` to get an app in api only mode. Since a lot of our rails backends going forward will be APIs it will make sense to figure out how to do this with the rails_apps_composer gem.

**Comment by samcdavid** [comment]
As a note, we had issues trying to do this with BNB and EMJ since we needed an admin system. I don't know if we want to roll full API.

**Comment by Mrjaco12** [comment]
None of these recipes are required. They're pretty much all optional and will just be packaged into "recommended" bundles that you can install together.

**Comment by Mrjaco12** [comment]
It turns out that you can complete this by implementing Issue #11 so I'll mark this as a dup and close.
