### ISSUE TITLE
We need a recipe for slim_lint

### ISSUE THREAD

**Issue by Mrjaco12** [spartansystems/spartan-composer-recipes#7]
A receipt for the gem [slim_lint](https://github.com/sds/slim-lint)

**Comment by TheAznShumai** [comment]
resolved on #12

**Comment by squaresurf** [comment]
@TheAznShumai you may find this useful in the future if you want to close an issue once your PR is merged - https://help.github.com/articles/closing-issues-via-commit-messages/
